<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="arduinoTrace" nsURI="arduinoTrace" nsPrefix="arduinoTrace">
  <eClassifiers xsi:type="ecore:EClass" name="Trace">
    <eStructuralFeatures xsi:type="ecore:EReference" name="statesTrace" upperBound="-1" eType="//States/State" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rootSteps" upperBound="-1" eType="//Steps/Step" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="arduino_tracedIntegerVariables" ordered="false" upperBound="-1" eType="//States/arduino/TracedIntegerVariable" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="arduino_tracedAnalogPins" ordered="false" upperBound="-1" eType="//States/arduino/TracedAnalogPin" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="arduino_tracedBooleanVariables" ordered="false" upperBound="-1" eType="//States/arduino/TracedBooleanVariable" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="arduino_tracedDigitalPins" ordered="false" upperBound="-1" eType="//States/arduino/TracedDigitalPin" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Arduino_BooleanModuleGet_Evaluate_Sequence" upperBound="-1" eType="//Steps/Arduino_BooleanModuleGet_Evaluate"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Arduino_ModuleAssignment_Execute_Sequence" upperBound="-1" eType="//Steps/Arduino_ModuleAssignment_Execute"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Arduino_While_Execute_Sequence" upperBound="-1" eType="//Steps/Arduino_While_Execute"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Arduino_Utilities_Execute_Sequence" upperBound="-1" eType="//Steps/Arduino_Utilities_Execute"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Arduino_Delay_Execute_Sequence" upperBound="-1" eType="//Steps/Arduino_Delay_Execute"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Arduino_If_Execute_Sequence" upperBound="-1" eType="//Steps/Arduino_If_Execute"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Arduino_VariableDeclaration_Execute_Sequence" upperBound="-1" eType="//Steps/Arduino_VariableDeclaration_Execute"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Arduino_VariableAssignment_Execute_Sequence" upperBound="-1" eType="//Steps/Arduino_VariableAssignment_Execute"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Arduino_Repeat_Execute_Sequence" upperBound="-1" eType="//Steps/Arduino_Repeat_Execute"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Arduino_IntegerModuleGet_Evaluate_Sequence" upperBound="-1" eType="//Steps/Arduino_IntegerModuleGet_Evaluate"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Arduino_BooleanConstant_Evaluate_Sequence" upperBound="-1" eType="//Steps/Arduino_BooleanConstant_Evaluate"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Arduino_ModuleAssignment_Call_Sequence" upperBound="-1" eType="//Steps/Arduino_ModuleAssignment_Call"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Arduino_IntegerConstant_Evaluate_Sequence" upperBound="-1" eType="//Steps/Arduino_IntegerConstant_Evaluate"/>
  </eClassifiers>
  <eSubpackages name="Steps" nsURI="arduinoTrace_Steps" nsPrefix="events">
    <eClassifiers xsi:type="ecore:EClass" name="SmallStep" abstract="true" eSuperTypes="//Steps/Step"/>
    <eClassifiers xsi:type="ecore:EClass" name="BigStep" abstract="true" eSuperTypes="//Steps/Step"/>
    <eClassifiers xsi:type="ecore:EClass" name="Step" abstract="true">
      <eStructuralFeatures xsi:type="ecore:EReference" name="startingState" lowerBound="1" eType="//States/State" eOpposite="//States/State/startedSteps"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="endingState" eType="//States/State" eOpposite="//States/State/endedSteps"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="RootFillStep" eSuperTypes="//Steps/SmallStep"/>
    <eClassifiers xsi:type="ecore:EClass" name="Arduino_BooleanModuleGet_Evaluate" eSuperTypes="//Steps/SmallStep //Steps/Arduino_ModuleAssignment_Execute_AbstractSubStep //Steps/Arduino_While_Execute_AbstractSubStep //Steps/Arduino_If_Execute_AbstractSubStep //Steps/Arduino_VariableAssignment_Execute_AbstractSubStep">
      <eStructuralFeatures xsi:type="ecore:EReference" name="this">
        <eType xsi:type="ecore:EClass" href="../../org.gemoc.arduino.melange/model-gen/ArduinoMT.ecore#//BooleanModuleGet"/>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Arduino_ModuleAssignment_Execute" eSuperTypes="//Steps/BigStep //Steps/Arduino_While_Execute_AbstractSubStep //Steps/Arduino_If_Execute_AbstractSubStep //Steps/Arduino_Repeat_Execute_AbstractSubStep //Steps/Arduino_ModuleAssignment_Call_AbstractSubStep">
      <eStructuralFeatures xsi:type="ecore:EReference" name="this">
        <eType xsi:type="ecore:EClass" href="../../org.gemoc.arduino.melange/model-gen/ArduinoMT.ecore#//ModuleAssignment"/>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="subSteps" upperBound="-1" eType="//Steps/Arduino_ModuleAssignment_Execute_AbstractSubStep" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Arduino_ModuleAssignment_Execute_AbstractSubStep" abstract="true"/>
    <eClassifiers xsi:type="ecore:EClass" name="Arduino_ModuleAssignment_Execute_FillStep" eSuperTypes="//Steps/Arduino_ModuleAssignment_Execute_AbstractSubStep"/>
    <eClassifiers xsi:type="ecore:EClass" name="Arduino_IntegerConstant_Evaluate" eSuperTypes="//Steps/Arduino_ModuleAssignment_Execute_AbstractSubStep //Steps/Arduino_While_Execute_AbstractSubStep //Steps/Arduino_If_Execute_AbstractSubStep //Steps/Arduino_VariableAssignment_Execute_AbstractSubStep //Steps/SmallStep">
      <eStructuralFeatures xsi:type="ecore:EReference" name="this">
        <eType xsi:type="ecore:EClass" href="../../org.gemoc.arduino.melange/model-gen/ArduinoMT.ecore#//IntegerConstant"/>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Arduino_BooleanConstant_Evaluate" eSuperTypes="//Steps/Arduino_ModuleAssignment_Execute_AbstractSubStep //Steps/Arduino_While_Execute_AbstractSubStep //Steps/Arduino_If_Execute_AbstractSubStep //Steps/Arduino_VariableAssignment_Execute_AbstractSubStep //Steps/SmallStep">
      <eStructuralFeatures xsi:type="ecore:EReference" name="this">
        <eType xsi:type="ecore:EClass" href="../../org.gemoc.arduino.melange/model-gen/ArduinoMT.ecore#//BooleanConstant"/>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Arduino_IntegerModuleGet_Evaluate" eSuperTypes="//Steps/Arduino_ModuleAssignment_Execute_AbstractSubStep //Steps/Arduino_While_Execute_AbstractSubStep //Steps/Arduino_If_Execute_AbstractSubStep //Steps/Arduino_VariableAssignment_Execute_AbstractSubStep //Steps/SmallStep">
      <eStructuralFeatures xsi:type="ecore:EReference" name="this">
        <eType xsi:type="ecore:EClass" href="../../org.gemoc.arduino.melange/model-gen/ArduinoMT.ecore#//IntegerModuleGet"/>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Arduino_While_Execute" eSuperTypes="//Steps/BigStep //Steps/Arduino_While_Execute_AbstractSubStep //Steps/Arduino_If_Execute_AbstractSubStep //Steps/Arduino_Repeat_Execute_AbstractSubStep">
      <eStructuralFeatures xsi:type="ecore:EReference" name="this">
        <eType xsi:type="ecore:EClass" href="../../org.gemoc.arduino.melange/model-gen/ArduinoMT.ecore#//While"/>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="subSteps" upperBound="-1" eType="//Steps/Arduino_While_Execute_AbstractSubStep" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Arduino_While_Execute_AbstractSubStep" abstract="true"/>
    <eClassifiers xsi:type="ecore:EClass" name="Arduino_While_Execute_FillStep" eSuperTypes="//Steps/Arduino_While_Execute_AbstractSubStep"/>
    <eClassifiers xsi:type="ecore:EClass" name="Arduino_Utilities_Execute" eSuperTypes="//Steps/Arduino_While_Execute_AbstractSubStep //Steps/SmallStep //Steps/Arduino_If_Execute_AbstractSubStep //Steps/Arduino_Repeat_Execute_AbstractSubStep">
      <eStructuralFeatures xsi:type="ecore:EReference" name="this">
        <eType xsi:type="ecore:EClass" href="../../org.gemoc.arduino.melange/model-gen/ArduinoMT.ecore#//Utilities"/>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Arduino_VariableAssignment_Execute" eSuperTypes="//Steps/Arduino_While_Execute_AbstractSubStep //Steps/Arduino_If_Execute_AbstractSubStep //Steps/BigStep //Steps/Arduino_Repeat_Execute_AbstractSubStep">
      <eStructuralFeatures xsi:type="ecore:EReference" name="this">
        <eType xsi:type="ecore:EClass" href="../../org.gemoc.arduino.melange/model-gen/ArduinoMT.ecore#//VariableAssignment"/>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="subSteps" upperBound="-1" eType="//Steps/Arduino_VariableAssignment_Execute_AbstractSubStep" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Arduino_If_Execute" eSuperTypes="//Steps/Arduino_While_Execute_AbstractSubStep //Steps/BigStep //Steps/Arduino_If_Execute_AbstractSubStep //Steps/Arduino_Repeat_Execute_AbstractSubStep">
      <eStructuralFeatures xsi:type="ecore:EReference" name="this">
        <eType xsi:type="ecore:EClass" href="../../org.gemoc.arduino.melange/model-gen/ArduinoMT.ecore#//If"/>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="subSteps" upperBound="-1" eType="//Steps/Arduino_If_Execute_AbstractSubStep" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Arduino_Delay_Execute" eSuperTypes="//Steps/Arduino_While_Execute_AbstractSubStep //Steps/SmallStep //Steps/Arduino_If_Execute_AbstractSubStep //Steps/Arduino_Repeat_Execute_AbstractSubStep">
      <eStructuralFeatures xsi:type="ecore:EReference" name="this">
        <eType xsi:type="ecore:EClass" href="../../org.gemoc.arduino.melange/model-gen/ArduinoMT.ecore#//Delay"/>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Arduino_VariableDeclaration_Execute" eSuperTypes="//Steps/Arduino_While_Execute_AbstractSubStep //Steps/Arduino_If_Execute_AbstractSubStep //Steps/SmallStep //Steps/Arduino_Repeat_Execute_AbstractSubStep">
      <eStructuralFeatures xsi:type="ecore:EReference" name="this">
        <eType xsi:type="ecore:EClass" href="../../org.gemoc.arduino.melange/model-gen/ArduinoMT.ecore#//VariableDeclaration"/>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Arduino_Repeat_Execute" eSuperTypes="//Steps/Arduino_While_Execute_AbstractSubStep //Steps/Arduino_If_Execute_AbstractSubStep //Steps/BigStep //Steps/Arduino_Repeat_Execute_AbstractSubStep">
      <eStructuralFeatures xsi:type="ecore:EReference" name="this">
        <eType xsi:type="ecore:EClass" href="../../org.gemoc.arduino.melange/model-gen/ArduinoMT.ecore#//Repeat"/>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="subSteps" upperBound="-1" eType="//Steps/Arduino_Repeat_Execute_AbstractSubStep" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Arduino_If_Execute_AbstractSubStep" abstract="true"/>
    <eClassifiers xsi:type="ecore:EClass" name="Arduino_If_Execute_FillStep" eSuperTypes="//Steps/Arduino_If_Execute_AbstractSubStep"/>
    <eClassifiers xsi:type="ecore:EClass" name="Arduino_VariableAssignment_Execute_AbstractSubStep" abstract="true"/>
    <eClassifiers xsi:type="ecore:EClass" name="Arduino_VariableAssignment_Execute_FillStep" eSuperTypes="//Steps/Arduino_VariableAssignment_Execute_AbstractSubStep"/>
    <eClassifiers xsi:type="ecore:EClass" name="Arduino_Repeat_Execute_AbstractSubStep" abstract="true"/>
    <eClassifiers xsi:type="ecore:EClass" name="Arduino_Repeat_Execute_FillStep" eSuperTypes="//Steps/Arduino_Repeat_Execute_AbstractSubStep"/>
    <eClassifiers xsi:type="ecore:EClass" name="Arduino_ModuleAssignment_Call" eSuperTypes="//Steps/BigStep">
      <eStructuralFeatures xsi:type="ecore:EReference" name="this">
        <eType xsi:type="ecore:EClass" href="../../org.gemoc.arduino.melange/model-gen/ArduinoMT.ecore#//ModuleAssignment"/>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="subSteps" upperBound="-1" eType="//Steps/Arduino_ModuleAssignment_Call_AbstractSubStep" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Arduino_ModuleAssignment_Call_AbstractSubStep" abstract="true"/>
    <eClassifiers xsi:type="ecore:EClass" name="Arduino_ModuleAssignment_Call_FillStep" eSuperTypes="//Steps/Arduino_ModuleAssignment_Call_AbstractSubStep"/>
  </eSubpackages>
  <eSubpackages name="States" nsURI="arduinoTrace_States" nsPrefix="tracedclasses">
    <eClassifiers xsi:type="ecore:EClass" name="State">
      <eStructuralFeatures xsi:type="ecore:EReference" name="startedSteps" upperBound="-1" eType="//Steps/Step" eOpposite="//Steps/Step/startingState"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="endedSteps" upperBound="-1" eType="//Steps/Step" eOpposite="//Steps/Step/endingState"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="pin_level_Values" ordered="false" upperBound="-1" eType="//States/Pin_level_Value" eOpposite="//States/Pin_level_Value/states"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="integerVariable_value_Values" ordered="false" upperBound="-1" eType="//States/IntegerVariable_value_Value" eOpposite="//States/IntegerVariable_value_Value/states"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="booleanVariable_value_Values" ordered="false" upperBound="-1" eType="//States/BooleanVariable_value_Value" eOpposite="//States/BooleanVariable_value_Value/states"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Pin_level_Value">
      <eAnnotations source="http://www.modelexecution.org/trace/XMOF">
        <details key="executionMetamodelElement"/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="level">
        <eAnnotations source="aspect"/>
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"/>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="parent" lowerBound="1" eType="//States/arduino/TracedPin" eOpposite="//States/arduino/TracedPin/levelSequence"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="states" lowerBound="1" upperBound="-1" eType="//States/State" eOpposite="//States/State/pin_level_Values"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="IntegerVariable_value_Value">
      <eAnnotations source="http://www.modelexecution.org/trace/XMOF">
        <details key="executionMetamodelElement"/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value">
        <eAnnotations source="aspect"/>
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"/>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="parent" lowerBound="1" eType="//States/arduino/TracedIntegerVariable" eOpposite="//States/arduino/TracedIntegerVariable/valueSequence"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="states" lowerBound="1" upperBound="-1" eType="//States/State" eOpposite="//States/State/integerVariable_value_Values"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="BooleanVariable_value_Value">
      <eAnnotations source="http://www.modelexecution.org/trace/XMOF">
        <details key="executionMetamodelElement"/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value">
        <eAnnotations source="aspect"/>
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="parent" lowerBound="1" eType="//States/arduino/TracedBooleanVariable" eOpposite="//States/arduino/TracedBooleanVariable/valueSequence"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="states" lowerBound="1" upperBound="-1" eType="//States/State" eOpposite="//States/State/booleanVariable_value_Values"/>
    </eClassifiers>
    <eSubpackages name="arduino" nsURI="arduinoTrace_arduino" nsPrefix="">
      <eClassifiers xsi:type="ecore:EClass" name="TracedPin" abstract="true">
        <eStructuralFeatures xsi:type="ecore:EReference" name="levelSequence" upperBound="-1" eType="//States/Pin_level_Value" containment="true" eOpposite="//States/Pin_level_Value/parent"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="TracedVariable" abstract="true" eSuperTypes="//States/arduino/TracedExpression //States/arduino/TracedNamedElement"/>
      <eClassifiers xsi:type="ecore:EClass" name="TracedIntegerVariable" eSuperTypes="//States/arduino/TracedVariable //States/arduino/TracedIntegerExpression">
        <eStructuralFeatures xsi:type="ecore:EReference" name="originalObject">
          <eType xsi:type="ecore:EClass" href="../../org.gemoc.arduino.melange/model-gen/ArduinoMT.ecore#//IntegerVariable"/>
        </eStructuralFeatures>
        <eStructuralFeatures xsi:type="ecore:EReference" name="valueSequence" upperBound="-1" eType="//States/IntegerVariable_value_Value" containment="true" eOpposite="//States/IntegerVariable_value_Value/parent"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="TracedAnalogPin" eSuperTypes="//States/arduino/TracedPin">
        <eStructuralFeatures xsi:type="ecore:EReference" name="originalObject">
          <eType xsi:type="ecore:EClass" href="../../org.gemoc.arduino.melange/model-gen/ArduinoMT.ecore#//AnalogPin"/>
        </eStructuralFeatures>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="TracedBooleanVariable" eSuperTypes="//States/arduino/TracedVariable //States/arduino/TracedBooleanExpression">
        <eStructuralFeatures xsi:type="ecore:EReference" name="originalObject">
          <eType xsi:type="ecore:EClass" href="../../org.gemoc.arduino.melange/model-gen/ArduinoMT.ecore#//BooleanVariable"/>
        </eStructuralFeatures>
        <eStructuralFeatures xsi:type="ecore:EReference" name="valueSequence" upperBound="-1" eType="//States/BooleanVariable_value_Value" containment="true" eOpposite="//States/BooleanVariable_value_Value/parent"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="TracedDigitalPin" eSuperTypes="//States/arduino/TracedPin">
        <eStructuralFeatures xsi:type="ecore:EReference" name="originalObject">
          <eType xsi:type="ecore:EClass" href="../../org.gemoc.arduino.melange/model-gen/ArduinoMT.ecore#//DigitalPin"/>
        </eStructuralFeatures>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="TracedExpression" abstract="true"/>
      <eClassifiers xsi:type="ecore:EClass" name="TracedIntegerExpression" abstract="true" eSuperTypes="//States/arduino/TracedExpression"/>
      <eClassifiers xsi:type="ecore:EClass" name="TracedNamedElement" abstract="true"/>
      <eClassifiers xsi:type="ecore:EClass" name="TracedBooleanExpression" abstract="true" eSuperTypes="//States/arduino/TracedExpression"/>
    </eSubpackages>
  </eSubpackages>
</ecore:EPackage>
