<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="arduino" nsURI="http://www.obeo.fr/arduino" nsPrefix="arduino">
  <eClassifiers xsi:type="ecore:EClass" name="Board" abstract="true" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="project" lowerBound="1"
        eType="#//Project" eOpposite="#//Project/boards"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="threads" upperBound="-1"
        eType="#//Thread"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Module" abstract="true" interface="true"
      eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="level" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DigitalPin" eSuperTypes="#//Pin">
    <eStructuralFeatures xsi:type="ecore:EReference" name="module" eType="#//ArduinoDigitalModule"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Pin" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="level" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject">
      <eAnnotations source="dynamic"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AnalogPin" eSuperTypes="#//Pin">
    <eStructuralFeatures xsi:type="ecore:EReference" name="module" eType="#//ArduinoAnalogModule"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Sketch" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="project" lowerBound="1"
        eType="#//Project" eOpposite="#//Project/sketch"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="threads" upperBound="-1"
        eType="#//Thread" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="channels" upperBound="-1"
        eType="#//Channel" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Project" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="boards" upperBound="-1"
        eType="#//Board" containment="true" eOpposite="#//Board/project"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sketch" eType="#//Sketch"
        containment="true" eOpposite="#//Sketch/project"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="links" upperBound="-1"
        eType="#//Link" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Instruction" abstract="true" eSuperTypes="#//NamedElement">
    <eOperations name="execute"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedBlock" eType="#//InstructionBlock"
        eOpposite="#//InstructionBlock/instructions"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ModuleAssignment" eSuperTypes="#//ModuleInstruction #//Assignment"/>
  <eClassifiers xsi:type="ecore:EClass" name="ModuleInstruction" abstract="true" eSuperTypes="#//Instruction">
    <eStructuralFeatures xsi:type="ecore:EReference" name="module" lowerBound="1"
        eType="#//Module"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Control" abstract="true" eSuperTypes="#//Instruction">
    <eStructuralFeatures xsi:type="ecore:EReference" name="block" lowerBound="1" eType="#//InstructionBlock"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Utilities" abstract="true" eSuperTypes="#//Instruction"/>
  <eClassifiers xsi:type="ecore:EClass" name="Delay" eSuperTypes="#//Utilities">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="unit" eType="#//Time"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Time">
    <eLiterals name="MilliSecond"/>
    <eLiterals name="MicroSecond"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NamedElement" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Repeat" eSuperTypes="#//Control">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="iteration" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="5"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ModuleGet" abstract="true" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="module" lowerBound="1"
        eType="#//Module"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="While" eSuperTypes="#//Control">
    <eStructuralFeatures xsi:type="ecore:EReference" name="condition" lowerBound="1"
        eType="#//BooleanExpression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BinaryExpression" abstract="true" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" lowerBound="1" eType="#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" eType="#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="BinaryIntegerOperatorKind">
    <eLiterals name="minus"/>
    <eLiterals name="plus" value="1"/>
    <eLiterals name="mul" value="2"/>
    <eLiterals name="div" value="3"/>
    <eLiterals name="min" value="4"/>
    <eLiterals name="max" value="5"/>
    <eLiterals name="pourcent" value="6"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Variable" abstract="true" eSuperTypes="#//Expression #//NamedElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="VariableAssignment" eSuperTypes="#//Instruction #//Assignment">
    <eStructuralFeatures xsi:type="ecore:EReference" name="variable" lowerBound="1"
        eType="#//Variable"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BinaryIntegerExpression" eSuperTypes="#//BinaryExpression #//IntegerExpression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operator" eType="#//BinaryIntegerOperatorKind"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BinaryBooleanExpression" eSuperTypes="#//BinaryExpression #//BooleanExpression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operator" eType="#//BinaryBooleanOperatorKind"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Expression" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Constant" abstract="true" eSuperTypes="#//Expression"/>
  <eClassifiers xsi:type="ecore:EClass" name="If" eSuperTypes="#//Control">
    <eStructuralFeatures xsi:type="ecore:EReference" name="condition" lowerBound="1"
        eType="#//BooleanExpression" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="elseBlock" eType="#//InstructionBlock"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IntegerConstant" eSuperTypes="#//Constant #//IntegerExpression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="0"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BooleanConstant" eSuperTypes="#//Constant #//BooleanExpression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BooleanExpression" abstract="true" eSuperTypes="#//Expression"/>
  <eClassifiers xsi:type="ecore:EClass" name="IntegerExpression" abstract="true" eSuperTypes="#//Expression"/>
  <eClassifiers xsi:type="ecore:EClass" name="Assignment" abstract="true" eSuperTypes="#//Instruction">
    <eStructuralFeatures xsi:type="ecore:EReference" name="operand" lowerBound="1"
        eType="#//Expression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IntegerVariable" eSuperTypes="#//Variable #//IntegerExpression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="initialValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"
        defaultValueLiteral="0">
      <eAnnotations source="dynamic"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BooleanVariable" eSuperTypes="#//Variable #//BooleanExpression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="initialValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"
        defaultValueLiteral="false">
      <eAnnotations source="dynamic"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BooleanModuleGet" eSuperTypes="#//ModuleGet #//BooleanExpression"/>
  <eClassifiers xsi:type="ecore:EClass" name="IntegerModuleGet" eSuperTypes="#//ModuleGet #//IntegerExpression"/>
  <eClassifiers xsi:type="ecore:EEnum" name="BinaryBooleanOperatorKind">
    <eLiterals name="inf" literal="inf"/>
    <eLiterals name="sup" value="1" literal="sup"/>
    <eLiterals name="infOrEqual" value="2" literal="infOrEqual"/>
    <eLiterals name="supOrEqual" value="3" literal="supOrEqual"/>
    <eLiterals name="equal" value="4" literal="equal"/>
    <eLiterals name="and" value="5" literal="and"/>
    <eLiterals name="or" value="6" literal="or"/>
    <eLiterals name="Different" value="7"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="UnaryIntegerOperatorKind">
    <eLiterals name="minus"/>
    <eLiterals name="squareRoot" value="1" literal="squareRoot"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="UnaryBooleanOperatorKind">
    <eLiterals name="not" literal="not"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UnaryExpression" abstract="true" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="operand" lowerBound="1"
        eType="#//Expression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UnaryBooleanExpression" eSuperTypes="#//UnaryExpression #//BooleanExpression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operator" eType="#//UnaryBooleanOperatorKind"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UnaryIntegerExpression" eSuperTypes="#//UnaryExpression #//IntegerExpression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operator" eType="#//UnaryIntegerOperatorKind"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VariableDeclaration" eSuperTypes="#//Instruction">
    <eStructuralFeatures xsi:type="ecore:EReference" name="variable" lowerBound="1"
        eType="#//Variable" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VariableRef" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="variable" lowerBound="1"
        eType="#//Variable"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LED" eSuperTypes="#//ArduinoDigitalModule"/>
  <eClassifiers xsi:type="ecore:EClass" name="PushButton" eSuperTypes="#//ArduinoDigitalModule"/>
  <eClassifiers xsi:type="ecore:EClass" name="Buzzer" eSuperTypes="#//ArduinoDigitalModule"/>
  <eClassifiers xsi:type="ecore:EClass" name="RotationSensor" eSuperTypes="#//ArduinoAnalogModule"/>
  <eClassifiers xsi:type="ecore:EClass" name="MicroServo" eSuperTypes="#//ArduinoDigitalModule"/>
  <eClassifiers xsi:type="ecore:EClass" name="InfraRedSensor" eSuperTypes="#//ArduinoDigitalModule"/>
  <eClassifiers xsi:type="ecore:EClass" name="AmbientLightSensor" eSuperTypes="#//ArduinoAnalogModule"/>
  <eClassifiers xsi:type="ecore:EClass" name="SoundSensor" eSuperTypes="#//ArduinoAnalogModule"/>
  <eClassifiers xsi:type="ecore:EClass" name="Fan" eSuperTypes="#//ArduinoDigitalModule"/>
  <eClassifiers xsi:type="ecore:EClass" name="MusicPlayer" eSuperTypes="#//ArduinoAnalogModule"/>
  <eClassifiers xsi:type="ecore:EClass" name="ArduinoModule" abstract="true" eSuperTypes="#//Module"/>
  <eClassifiers xsi:type="ecore:EClass" name="ArduinoBoard" eSuperTypes="#//Board">
    <eStructuralFeatures xsi:type="ecore:EReference" name="digitalPins" upperBound="-1"
        eType="#//DigitalPin" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="analogPins" upperBound="-1"
        eType="#//AnalogPin" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ArduinoDigitalModule" abstract="true"
      eSuperTypes="#//ArduinoModule"/>
  <eClassifiers xsi:type="ecore:EClass" name="ArduinoAnalogModule" abstract="true"
      eSuperTypes="#//ArduinoModule"/>
  <eClassifiers xsi:type="ecore:EClass" name="Thread" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="blocks" upperBound="-1"
        eType="#//ThreadInstructionBlock" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="channels" upperBound="-1"
        eType="#//Channel" eOpposite="#//Channel/source"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="currentInstruction" eType="#//Instruction"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="first" eType="#//ThreadInstructionBlock"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="last" eType="#//ThreadInstructionBlock"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nbCycle" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Channel" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
        eType="#//Thread" eOpposite="#//Thread/channels"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="#//Thread"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="inRate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="outRate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="capacity" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="currentSize" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Link" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="inBoard" lowerBound="1"
        eType="#//Board"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outBoard" lowerBound="1"
        eType="#//Board"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="channels" upperBound="-1"
        eType="#//Channel"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SynchronizationBlock" eSuperTypes="#//ThreadInstructionBlock"/>
  <eClassifiers xsi:type="ecore:EClass" name="InstructionBlock" eSuperTypes="#//ThreadInstructionBlock">
    <eStructuralFeatures xsi:type="ecore:EReference" name="instructions" upperBound="-1"
        eType="#//Instruction" containment="true" eOpposite="#//Instruction/ownedBlock"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ThreadInstructionBlock" abstract="true"
      eSuperTypes="#//NamedElement">
    <eOperations name="execute"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="thread" eType="#//Thread"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="next" eType="#//ThreadInstructionBlock"/>
  </eClassifiers>
</ecore:EPackage>
