<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="arduinoTrace" nsURI="arduinoTrace" nsPrefix="arduinoTrace">
  <eClassifiers xsi:type="ecore:EClass" name="Trace">
    <eStructuralFeatures xsi:type="ecore:EReference" name="statesTrace" upperBound="-1"
        eType="#//State" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="steps" lowerBound="1" eType="#//Steps/Steps"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tracedObjects" lowerBound="1"
        eType="#//Traced/TracedObjects" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="State">
    <eStructuralFeatures xsi:type="ecore:EReference" name="followingStep" eType="#//Steps/SmallStep"
        eOpposite="#//Steps/SmallStep/precedingState"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="startedBigSteps" upperBound="-1"
        eType="#//Steps/BigStep" eOpposite="#//Steps/BigStep/startingState"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="endedBigSteps" upperBound="-1"
        eType="#//Steps/BigStep" eOpposite="#//Steps/BigStep/endingState"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="variable_value_Values"
        ordered="false" upperBound="-1" eType="#//Values/Variable_value_Value" eOpposite="#//Values/Variable_value_Value/states"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="pin_level_Values" ordered="false"
        upperBound="-1" eType="#//Values/Pin_level_Value" eOpposite="#//Values/Pin_level_Value/states"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="numberValue_value_Values"
        ordered="false" upperBound="-1" eType="#//Values/NumberValue_value_Value"
        eOpposite="#//Values/NumberValue_value_Value/states"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="stringValue_value_Values"
        ordered="false" upperBound="-1" eType="#//Values/StringValue_value_Value"
        eOpposite="#//Values/StringValue_value_Value/states"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="booleanValue_value_Values"
        ordered="false" upperBound="-1" eType="#//Values/BooleanValue_value_Value"
        eOpposite="#//Values/BooleanValue_value_Value/states"/>
  </eClassifiers>
  <eSubpackages name="Steps" nsURI="arduinoTrace_Steps" nsPrefix="events">
    <eClassifiers xsi:type="ecore:EClass" name="SmallStep" abstract="true">
      <eStructuralFeatures xsi:type="ecore:EReference" name="precedingState" lowerBound="1"
          eType="#//State" eOpposite="#//State/followingStep"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Steps">
      <eStructuralFeatures xsi:type="ecore:EReference" name="Arduino_Status_Execute_FillStep_Trace"
          upperBound="-1" eType="#//Steps/Arduino_Status_Execute_FillStep" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="Arduino_Project_Setup_FillStep_Trace"
          upperBound="-1" eType="#//Steps/Arduino_Project_Setup_FillStep" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="Arduino_Repeat_Execute_FillStep_Trace"
          upperBound="-1" eType="#//Steps/Arduino_Repeat_Execute_FillStep" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="Arduino_Level_Execute_FillStep_Trace"
          upperBound="-1" eType="#//Steps/Arduino_Level_Execute_FillStep" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="Arduino_Set_Execute_FillStep_Trace"
          upperBound="-1" eType="#//Steps/Arduino_Set_Execute_FillStep" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="Arduino_Delay_Execute_Trace"
          upperBound="-1" eType="#//Steps/Arduino_Delay_Execute" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="Arduino_Utilities_Call_FillStep_Trace"
          upperBound="-1" eType="#//Steps/Arduino_Utilities_Call_FillStep" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="Arduino_FunctionCall_Execute_FillStep_Trace"
          upperBound="-1" eType="#//Steps/Arduino_FunctionCall_Execute_FillStep" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="Arduino_Utilities_Execute_Trace"
          upperBound="-1" eType="#//Steps/Arduino_Utilities_Execute" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="Arduino_If_Execute_FillStep_Trace"
          upperBound="-1" eType="#//Steps/Arduino_If_Execute_FillStep" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="Arduino_While_Execute_FillStep_Trace"
          upperBound="-1" eType="#//Steps/Arduino_While_Execute_FillStep" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="Arduino_Status_Call_FillStep_Trace"
          upperBound="-1" eType="#//Steps/Arduino_Status_Call_FillStep" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="FillStep_Trace" upperBound="-1"
          eType="#//Steps/FillStep" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="Arduino_Status_Execute_Trace"
          upperBound="-1" eType="#//Steps/Arduino_Status_Execute" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="Arduino_Project_Setup_Trace"
          upperBound="-1" eType="#//Steps/Arduino_Project_Setup" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="Arduino_Repeat_Execute_Trace"
          upperBound="-1" eType="#//Steps/Arduino_Repeat_Execute" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="Arduino_Level_Execute_Trace"
          upperBound="-1" eType="#//Steps/Arduino_Level_Execute" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="Arduino_Set_Execute_Trace"
          upperBound="-1" eType="#//Steps/Arduino_Set_Execute" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="Arduino_Utilities_Call_Trace"
          upperBound="-1" eType="#//Steps/Arduino_Utilities_Call" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="Arduino_FunctionCall_Execute_Trace"
          upperBound="-1" eType="#//Steps/Arduino_FunctionCall_Execute" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="Arduino_If_Execute_Trace"
          upperBound="-1" eType="#//Steps/Arduino_If_Execute" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="Arduino_While_Execute_Trace"
          upperBound="-1" eType="#//Steps/Arduino_While_Execute" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="Arduino_Status_Call_Trace"
          upperBound="-1" eType="#//Steps/Arduino_Status_Call" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="BigStep" abstract="true">
      <eStructuralFeatures xsi:type="ecore:EReference" name="startingState" lowerBound="1"
          eType="#//State" eOpposite="#//State/startedBigSteps"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="endingState" eType="#//State"
          eOpposite="#//State/endedBigSteps"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Arduino_Status_Execute_AbstractSubStep"
        abstract="true"/>
    <eClassifiers xsi:type="ecore:EClass" name="Arduino_Status_Execute_FillStep" eSuperTypes="#//Steps/Arduino_Status_Execute_AbstractSubStep #//Steps/SmallStep"/>
    <eClassifiers xsi:type="ecore:EClass" name="Arduino_Project_Setup_AbstractSubStep"
        abstract="true"/>
    <eClassifiers xsi:type="ecore:EClass" name="Arduino_Project_Setup_FillStep" eSuperTypes="#//Steps/Arduino_Project_Setup_AbstractSubStep #//Steps/SmallStep"/>
    <eClassifiers xsi:type="ecore:EClass" name="Arduino_Repeat_Execute_AbstractSubStep"
        abstract="true"/>
    <eClassifiers xsi:type="ecore:EClass" name="Arduino_Repeat_Execute_FillStep" eSuperTypes="#//Steps/Arduino_Repeat_Execute_AbstractSubStep #//Steps/SmallStep"/>
    <eClassifiers xsi:type="ecore:EClass" name="Arduino_Level_Execute_AbstractSubStep"
        abstract="true"/>
    <eClassifiers xsi:type="ecore:EClass" name="Arduino_Level_Execute_FillStep" eSuperTypes="#//Steps/Arduino_Level_Execute_AbstractSubStep #//Steps/SmallStep"/>
    <eClassifiers xsi:type="ecore:EClass" name="Arduino_Set_Execute_AbstractSubStep"
        abstract="true"/>
    <eClassifiers xsi:type="ecore:EClass" name="Arduino_Set_Execute_FillStep" eSuperTypes="#//Steps/Arduino_Set_Execute_AbstractSubStep #//Steps/SmallStep"/>
    <eClassifiers xsi:type="ecore:EClass" name="Arduino_Delay_Execute" eSuperTypes="#//Steps/SmallStep">
      <eStructuralFeatures xsi:type="ecore:EReference" name="this" eType="ecore:EClass ../../fr.obeo.dsl.arduino/model/arduino.ecore#//Delay"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Arduino_Utilities_Call_AbstractSubStep"
        abstract="true"/>
    <eClassifiers xsi:type="ecore:EClass" name="Arduino_Utilities_Call_FillStep" eSuperTypes="#//Steps/Arduino_Utilities_Call_AbstractSubStep #//Steps/SmallStep"/>
    <eClassifiers xsi:type="ecore:EClass" name="Arduino_FunctionCall_Execute_AbstractSubStep"
        abstract="true"/>
    <eClassifiers xsi:type="ecore:EClass" name="Arduino_FunctionCall_Execute_FillStep"
        eSuperTypes="#//Steps/Arduino_FunctionCall_Execute_AbstractSubStep #//Steps/SmallStep"/>
    <eClassifiers xsi:type="ecore:EClass" name="Arduino_Utilities_Execute" eSuperTypes="#//Steps/SmallStep">
      <eStructuralFeatures xsi:type="ecore:EReference" name="this" eType="ecore:EClass ../../fr.obeo.dsl.arduino/model/arduino.ecore#//Utilities"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Arduino_If_Execute_AbstractSubStep"
        abstract="true"/>
    <eClassifiers xsi:type="ecore:EClass" name="Arduino_If_Execute_FillStep" eSuperTypes="#//Steps/Arduino_If_Execute_AbstractSubStep #//Steps/SmallStep"/>
    <eClassifiers xsi:type="ecore:EClass" name="Arduino_While_Execute_AbstractSubStep"
        abstract="true"/>
    <eClassifiers xsi:type="ecore:EClass" name="Arduino_While_Execute_FillStep" eSuperTypes="#//Steps/Arduino_While_Execute_AbstractSubStep #//Steps/SmallStep"/>
    <eClassifiers xsi:type="ecore:EClass" name="Arduino_Status_Call_AbstractSubStep"
        abstract="true"/>
    <eClassifiers xsi:type="ecore:EClass" name="Arduino_Status_Call_FillStep" eSuperTypes="#//Steps/Arduino_Status_Call_AbstractSubStep #//Steps/SmallStep"/>
    <eClassifiers xsi:type="ecore:EClass" name="FillStep" eSuperTypes="#//Steps/SmallStep"/>
    <eClassifiers xsi:type="ecore:EClass" name="Arduino_Status_Execute" eSuperTypes="#//Steps/BigStep">
      <eStructuralFeatures xsi:type="ecore:EReference" name="this" eType="ecore:EClass ../../fr.obeo.dsl.arduino/model/arduino.ecore#//Status"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="subSteps" upperBound="-1"
          eType="#//Steps/Arduino_Status_Execute_AbstractSubStep"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Arduino_Project_Setup" eSuperTypes="#//Steps/BigStep">
      <eStructuralFeatures xsi:type="ecore:EReference" name="this" eType="ecore:EClass ../../fr.obeo.dsl.arduino/model/arduino.ecore#//Project"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="subSteps" upperBound="-1"
          eType="#//Steps/Arduino_Project_Setup_AbstractSubStep"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Arduino_Repeat_Execute" eSuperTypes="#//Steps/BigStep">
      <eStructuralFeatures xsi:type="ecore:EReference" name="this" eType="ecore:EClass ../../fr.obeo.dsl.arduino/model/arduino.ecore#//Repeat"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="subSteps" upperBound="-1"
          eType="#//Steps/Arduino_Repeat_Execute_AbstractSubStep"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Arduino_Level_Execute" eSuperTypes="#//Steps/BigStep">
      <eStructuralFeatures xsi:type="ecore:EReference" name="this" eType="ecore:EClass ../../fr.obeo.dsl.arduino/model/arduino.ecore#//Level"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="subSteps" upperBound="-1"
          eType="#//Steps/Arduino_Level_Execute_AbstractSubStep"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Arduino_Set_Execute" eSuperTypes="#//Steps/BigStep">
      <eStructuralFeatures xsi:type="ecore:EReference" name="this" eType="ecore:EClass ../../fr.obeo.dsl.arduino/model/arduino.ecore#//Set"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="subSteps" upperBound="-1"
          eType="#//Steps/Arduino_Set_Execute_AbstractSubStep"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Arduino_Utilities_Call" eSuperTypes="#//Steps/BigStep">
      <eStructuralFeatures xsi:type="ecore:EReference" name="this" eType="ecore:EClass ../../fr.obeo.dsl.arduino/model/arduino.ecore#//Utilities"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="subSteps" upperBound="-1"
          eType="#//Steps/Arduino_Utilities_Call_AbstractSubStep"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Arduino_FunctionCall_Execute" eSuperTypes="#//Steps/BigStep">
      <eStructuralFeatures xsi:type="ecore:EReference" name="this" eType="ecore:EClass ../../fr.obeo.dsl.arduino/model/arduino.ecore#//FunctionCall"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="subSteps" upperBound="-1"
          eType="#//Steps/Arduino_FunctionCall_Execute_AbstractSubStep"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Arduino_If_Execute" eSuperTypes="#//Steps/BigStep">
      <eStructuralFeatures xsi:type="ecore:EReference" name="this" eType="ecore:EClass ../../fr.obeo.dsl.arduino/model/arduino.ecore#//If"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="subSteps" upperBound="-1"
          eType="#//Steps/Arduino_If_Execute_AbstractSubStep"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Arduino_While_Execute" eSuperTypes="#//Steps/BigStep">
      <eStructuralFeatures xsi:type="ecore:EReference" name="this" eType="ecore:EClass ../../fr.obeo.dsl.arduino/model/arduino.ecore#//While"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="subSteps" upperBound="-1"
          eType="#//Steps/Arduino_While_Execute_AbstractSubStep"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Arduino_Status_Call" eSuperTypes="#//Steps/BigStep">
      <eStructuralFeatures xsi:type="ecore:EReference" name="this" eType="ecore:EClass ../../fr.obeo.dsl.arduino/model/arduino.ecore#//Status"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="subSteps" upperBound="-1"
          eType="#//Steps/Arduino_Status_Call_AbstractSubStep"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="Values" nsURI="arduinoTrace_Values" nsPrefix="states">
    <eClassifiers xsi:type="ecore:EClass" name="Variable_value_Value">
      <eAnnotations source="http://www.modelexecution.org/trace/XMOF">
        <details key="executionMetamodelElement"/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="value" eType="#//Traced/arduino/TracedValue">
        <eAnnotations/>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="parent" lowerBound="1"
          eType="#//Traced/arduino/TracedVariable" eOpposite="#//Traced/arduino/TracedVariable/valueTrace"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="states" lowerBound="1"
          upperBound="-1" eType="#//State" eOpposite="#//State/variable_value_Values"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Pin_level_Value">
      <eAnnotations source="http://www.modelexecution.org/trace/XMOF">
        <details key="executionMetamodelElement"/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="level" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt">
        <eAnnotations/>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="parent" lowerBound="1"
          eType="#//Traced/arduino/TracedPin" eOpposite="#//Traced/arduino/TracedPin/levelTrace"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="states" lowerBound="1"
          upperBound="-1" eType="#//State" eOpposite="#//State/pin_level_Values"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="NumberValue_value_Value">
      <eAnnotations source="http://www.modelexecution.org/trace/XMOF">
        <details key="executionMetamodelElement"/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="parent" lowerBound="1"
          eType="#//Traced/arduino/TracedNumberValue" eOpposite="#//Traced/arduino/TracedNumberValue/valueTrace"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="states" lowerBound="1"
          upperBound="-1" eType="#//State" eOpposite="#//State/numberValue_value_Values"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="StringValue_value_Value">
      <eAnnotations source="http://www.modelexecution.org/trace/XMOF">
        <details key="executionMetamodelElement"/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="parent" lowerBound="1"
          eType="#//Traced/arduino/TracedStringValue" eOpposite="#//Traced/arduino/TracedStringValue/valueTrace"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="states" lowerBound="1"
          upperBound="-1" eType="#//State" eOpposite="#//State/stringValue_value_Values"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="BooleanValue_value_Value">
      <eAnnotations source="http://www.modelexecution.org/trace/XMOF">
        <details key="executionMetamodelElement"/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="parent" lowerBound="1"
          eType="#//Traced/arduino/TracedBooleanValue" eOpposite="#//Traced/arduino/TracedBooleanValue/valueTrace"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="states" lowerBound="1"
          upperBound="-1" eType="#//State" eOpposite="#//State/booleanValue_value_Values"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="Traced" nsURI="arduinoTrace_Traced" nsPrefix="tracedclasses">
    <eClassifiers xsi:type="ecore:EClass" name="TracedObjects">
      <eStructuralFeatures xsi:type="ecore:EReference" name="arduino_tracedDigitalPins"
          ordered="false" upperBound="-1" eType="#//Traced/arduino/TracedDigitalPin"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="arduino_tracedAnalogPins"
          ordered="false" upperBound="-1" eType="#//Traced/arduino/TracedAnalogPin"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="arduino_tracedVariables"
          ordered="false" upperBound="-1" eType="#//Traced/arduino/TracedVariable"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="arduino_tracedNumberValues"
          ordered="false" upperBound="-1" eType="#//Traced/arduino/TracedNumberValue"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="arduino_tracedStringValues"
          ordered="false" upperBound="-1" eType="#//Traced/arduino/TracedStringValue"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="arduino_tracedBooleanValues"
          ordered="false" upperBound="-1" eType="#//Traced/arduino/TracedBooleanValue"
          containment="true"/>
    </eClassifiers>
    <eSubpackages name="arduino" nsURI="arduinoTrace_arduino" nsPrefix="">
      <eClassifiers xsi:type="ecore:EClass" name="TracedDigitalPin" eSuperTypes="#//Traced/arduino/TracedPin">
        <eStructuralFeatures xsi:type="ecore:EReference" name="originalObject" eType="ecore:EClass ../../fr.obeo.dsl.arduino/model/arduino.ecore#//DigitalPin"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="TracedAnalogPin" eSuperTypes="#//Traced/arduino/TracedPin">
        <eStructuralFeatures xsi:type="ecore:EReference" name="originalObject" eType="ecore:EClass ../../fr.obeo.dsl.arduino/model/arduino.ecore#//AnalogPin"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="TracedParameter" abstract="true">
        <eStructuralFeatures xsi:type="ecore:EReference" name="definition" eType="ecore:EClass ../../fr.obeo.dsl.arduino/model/arduino.ecore#//ParameterDefinition"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="TracedVariable" eSuperTypes="#//Traced/arduino/TracedExpression #//Traced/arduino/TracedInstruction">
        <eStructuralFeatures xsi:type="ecore:EReference" name="value" eType="ecore:EClass ../../fr.obeo.dsl.arduino/model/arduino.ecore#//Value">
          <eAnnotations/>
        </eStructuralFeatures>
        <eStructuralFeatures xsi:type="ecore:EReference" name="originalObject" eType="ecore:EClass ../../fr.obeo.dsl.arduino/model/arduino.ecore#//Variable"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="valueTrace" upperBound="-1"
            eType="#//Values/Variable_value_Value" containment="true" eOpposite="#//Values/Variable_value_Value/parent"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="TracedValue" abstract="true"/>
      <eClassifiers xsi:type="ecore:EClass" name="TracedPin" abstract="true">
        <eStructuralFeatures xsi:type="ecore:EReference" name="levelTrace" upperBound="-1"
            eType="#//Values/Pin_level_Value" containment="true" eOpposite="#//Values/Pin_level_Value/parent"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="TracedNumberValue" eSuperTypes="#//Traced/arduino/TracedValue">
        <eStructuralFeatures xsi:type="ecore:EReference" name="valueTrace" upperBound="-1"
            eType="#//Values/NumberValue_value_Value" containment="true" eOpposite="#//Values/NumberValue_value_Value/parent"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="TracedStringValue" eSuperTypes="#//Traced/arduino/TracedValue">
        <eStructuralFeatures xsi:type="ecore:EReference" name="valueTrace" upperBound="-1"
            eType="#//Values/StringValue_value_Value" containment="true" eOpposite="#//Values/StringValue_value_Value/parent"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="TracedInstruction" abstract="true">
        <eStructuralFeatures xsi:type="ecore:EReference" name="previous" eType="#//Traced/arduino/TracedInstruction"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="next" eType="#//Traced/arduino/TracedInstruction"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="TracedExpression" abstract="true"
          eSuperTypes="#//Traced/arduino/TracedInstruction #//Traced/arduino/TracedParameter"/>
      <eClassifiers xsi:type="ecore:EClass" name="TracedBooleanValue" eSuperTypes="#//Traced/arduino/TracedValue">
        <eStructuralFeatures xsi:type="ecore:EReference" name="valueTrace" upperBound="-1"
            eType="#//Values/BooleanValue_value_Value" containment="true" eOpposite="#//Values/BooleanValue_value_Value/parent"/>
      </eClassifiers>
    </eSubpackages>
  </eSubpackages>
</ecore:EPackage>
