name = org.gemoc.arduino.concurrent.XArduino

 ecore = platform:/resource/org.gemoc.arduino.concurrent.xarduino/model/XArduino.ecore

 k3 = org.gemoc.arduino.concurrent.xarduino.aspects.ArduinoCommunicationModule_PushAspect,org.gemoc.arduino.concurrent.xarduino.aspects.BinaryBooleanExpression_EvaluableAspect,org.gemoc.arduino.concurrent.xarduino.aspects.BinaryExpression_EvaluableAspect,org.gemoc.arduino.concurrent.xarduino.aspects.BinaryIntegerExpression_EvaluableAspect,org.gemoc.arduino.concurrent.xarduino.aspects.BluetoothTransceiver_PushAspect,org.gemoc.arduino.concurrent.xarduino.aspects.BooleanConstant_ExecutableAspect,org.gemoc.arduino.concurrent.xarduino.aspects.BooleanExpression_EvaluableAspect,org.gemoc.arduino.concurrent.xarduino.aspects.BooleanModuleGet_ExecutableAspect,org.gemoc.arduino.concurrent.xarduino.aspects.BooleanVariable_EvaluableAspect,org.gemoc.arduino.concurrent.xarduino.aspects.Constant_EvaluableAspect,org.gemoc.arduino.concurrent.xarduino.aspects.Control_EvaluableAspect,org.gemoc.arduino.concurrent.xarduino.aspects.Control_ExecutableAspect,org.gemoc.arduino.concurrent.xarduino.aspects.Delay_ExecutableAspect,org.gemoc.arduino.concurrent.xarduino.aspects.Expression_EvaluableAspect,org.gemoc.arduino.concurrent.xarduino.aspects.If_EvaluableAspect,org.gemoc.arduino.concurrent.xarduino.aspects.Instruction_ExecutableAspect,org.gemoc.arduino.concurrent.xarduino.aspects.IntegerConstant_ExecutableAspect,org.gemoc.arduino.concurrent.xarduino.aspects.IntegerExpression_EvaluableAspect,org.gemoc.arduino.concurrent.xarduino.aspects.IntegerModuleGet_ExecutableAspect,org.gemoc.arduino.concurrent.xarduino.aspects.IntegerVariable_EvaluableAspect,org.gemoc.arduino.concurrent.xarduino.aspects.ModuleAssignment_ExecutableAspect,org.gemoc.arduino.concurrent.xarduino.aspects.ModuleInstruction_ExecutableAspect,org.gemoc.arduino.concurrent.xarduino.aspects.Module_UtilitiesAspect,org.gemoc.arduino.concurrent.xarduino.aspects.Pin_EvaluableAspect,org.gemoc.arduino.concurrent.xarduino.aspects.Project_ExecutableAspect,org.gemoc.arduino.concurrent.xarduino.aspects.PushButton_ToggleAspect,org.gemoc.arduino.concurrent.xarduino.aspects.Repeat_EvaluableAspect,org.gemoc.arduino.concurrent.xarduino.aspects.Utilities_ExecutableAspect,org.gemoc.arduino.concurrent.xarduino.aspects.VariableAssignment_ExecutableAspect,org.gemoc.arduino.concurrent.xarduino.aspects.VariableDeclaration_ExecutableAspect,org.gemoc.arduino.concurrent.xarduino.aspects.VariableRef_EvaluableAspect,org.gemoc.arduino.concurrent.xarduino.aspects.Variable_EvaluableAspect,org.gemoc.arduino.concurrent.xarduino.aspects.While_EvaluableAspect

 ecl = /org.gemoc.arduino.concurrent.moc.dse/ecl/arduinoML.ecl

 metaprog = org.eclipse.gemoc.metaprog.moccml
